# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing Simulations

on:
  push:
    branches: [ "master", "testing-workflows" ]
  pull_request:
    branches: [ "master", "testing-workflows" ]

permissions:
  contents: read
  packages: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install flake8 poetry
    - name: Set up GitHub token
      run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
    - name: Setup with Poetry
      run: |
        poetry lock
        poetry install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Test
      run: |
        poetry run python examples/test_new_changes.py
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: latest 
        use-public-rspm: true
    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::ggplot2
          any::dplyr
          any::patchwork
          any::stringr
    - name: Upload image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: model-comparison-image
        path: test_outputs/comparison_plot.png
        
