# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing Simulations

on:
  push:
    branches: [ "master", "testing-workflows" ]
  pull_request:
    branches: [ "master", "testing-workflows" ]

permissions:
  actions: read
  contents: write
  pull-requests: write
  packages: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install flake8 poetry
    - name: Set up GitHub token
      run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
    - name: Setup Env with Poetry
      run: |
        poetry lock
        poetry install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Model
      run: |
        poetry run python examples/test_new_changes.py
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: latest 
        use-public-rspm: true
    - name: Install R Dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::ggplot2
          any::dplyr
          any::patchwork
          any::stringr
    - name: Run Visualization Code in R
      run: Rscript test_outputs/compare_model_to_r.R
    - name: Upload image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: model-comparison-image
        path: test_outputs/comparison_plot.png

  comment-results:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Image URL and create comment 
        uses: actions/github-script@v7
        with:
          script: |
            async function runAsync() {
              const artifact_list = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.runId
              })
              console.log(artifact_list)
              const image_artifact = artifact_list.data.artifacts.find(artifact => artifact.name === "comparison_plot.png")
              console.log(image_artifact)
              const image_url = image_artifact.url
              console.log(image_url)

              const comment_body = 'Automated Test has been run. Here is the plot comparing the new code\'s output ![comparison_plot](' + image_url + ')'
              
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment_body
              })
            }
            await runAsync()
        
